detailedreports: fix incomplete init
Missing call to super().__init__(), causing Harvest object internal attributes
such as 'uri' to not be initialised/instantiated, causing an AttributeError
to be raised upong the issue of the first request.

time_entries = reports.detailed_time(time_frame='This Week')
  File "/usr/local/lib/python3.8/site-packages/harvest/detailedreports.py", line 157, in detailed_time
    time_entries = self.time_entries(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/harvest/harvest.py", line 544, in time_entries
    return from_dict(data_class=TimeEntries, data=self._get(url))
  File "/usr/local/lib/python3.8/site-packages/harvest/harvest.py", line 849, in _get
    return self._request('GET', path, data)
  File "/usr/local/lib/python3.8/site-packages/harvest/harvest.py", line 861, in _request
    url = '{self.uri}{path}'.format(self=self, path=path)
  File "/usr/local/lib/python3.8/site-packages/harvest/harvest.py", line 61, in uri
    return self.__uri
AttributeError: 'DetailedReports' object has no attribute '_Harvest__uri'

Since there is no effective need to handle variable arguments, just reuse same arguments
as Harvest::__init__().

Signed-off-by: Patrick Titiano <ptitiano@baylibre.com>