reports: timeframe: fix wrong dict keys
Code was creating a dict with 'from' and 'to' keys instead of expected
'from_date' and 'to_date', causing the following exception to be raised:

TypeError: time_entries() got an unexpected keyword argument 'from'

Signed-off-by: Patrick Titiano <ptitiano@baylibre.com>